version: '3.8'

services:

  postgres:
    image: postgres:16-alpine
    container_name: oficina-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: oficina
      POSTGRES_USER: oficina
      POSTGRES_PASSWORD: oficina123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oficina -d oficina"]
      interval: 10s
      timeout: 5s
      retries: 5

  oficina-api:
    build: .
    container_name: oficina-mecanica-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: default
      DB_HOST: postgres
      DB_PASSWORD: oficina123
      JWT_PUBLIC_KEY: file:/app/keys/jwt.public.key
      JWT_PRIVATE_KEY: file:/app/keys/jwt.private.key
      GMAIL_SMTP_USERNAME: ${GMAIL_SMTP_USERNAME:-}
      GMAIL_SMTP_PASSWORD: ${GMAIL_SMTP_PASSWORD:-}
      APP_PUBLIC_BASE_URL: ${APP_PUBLIC_BASE_URL:-http://localhost:8080}
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY:-}
      NEW_RELIC_APP_NAME: ${NEW_RELIC_APP_NAME:-oficina-api-local}
      NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED: ${NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED:-true}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
